SEED=42
INDICADOR_DEV_DISPONIVEL = 'INDEFINIDO'
#
# DATASETS
ENDERECO_DATASET_DESENVOLVEDORES = 'space_dataset_final_anonimizado.csv'
ENDERECO_DATASET_SOLUCOES_ENCONTRADAS = './solucoes/solucoes_encontradas'
#
# LOGS
ENDERECO_LOG_OTIMIZACAO = './log/log_otimizacao'
#
# HYPERVOLUME
ENDERECO_HYPERVOLUME_SOLUCOES_ENCONTRADAS = './hypervolume/hypervolume.csv'
#
# OTIMIZAÇÃO
TAMANHO_POPULACAO_INICIAL = 1250
PERCENTUAL_DESCENDENTES_EM_RELACAO_AO_TAMANHO_DA_POPULACAO_INICIAL = 0.7
QUANTIDADE_DE_GERACOES_QUE_DEFINEM_O_TERMINO_DA_OTIMIZACAO = 100
#
# CALCULADAS
QUANTIDADE_DESCENDENTES = int(round(TAMANHO_POPULACAO_INICIAL * PERCENTUAL_DESCENDENTES_EM_RELACAO_AO_TAMANHO_DA_POPULACAO_INICIAL))
RESUMO_EXECUCAO = { 'POP_SIZE' : TAMANHO_POPULACAO_INICIAL, 'N_OFFSPRINGS': QUANTIDADE_DESCENDENTES, 'N_GEN': QUANTIDADE_DE_GERACOES_QUE_DEFINEM_O_TERMINO_DA_OTIMIZACAO }
IDENTIFICADOR_EXECUCAO = ''.join([ '.' + key + '_' + str(RESUMO_EXECUCAO[key]) for key in RESUMO_EXECUCAO ])